services:

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: eld
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

  backend:
    build: ./backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    depends_on:
      - postgres