# Generated by Django 6.0.6 on 2026-06-21 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_cycle_used_hours", models.FloatField()),
                ("total_distance_miles", models.FloatField(default=0)),
                ("total_duration_hours", models.FloatField(default=0)),
                ("route_geometry", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stop_type",
                    models.CharField(
                        choices=[
                            ("start", "Start"),
                            ("pickup", "Pickup"),
                            ("dropoff", "Dropoff"),
                            ("rest", "Rest"),
                            ("fuel", "Fuel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("duration_minutes", models.IntegerField()),
                ("sequence", models.IntegerField(default=0)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "id"],
            },
        ),
    ]
